Fix to tf.keras.utils.plot_model() error

Fix to #17633
'Model' object has no attribute '_container_nodes' error when using tf.keras.utils.plot_model().
Replaced
if node_key in model.container_nodes:
with
if node_key in model._network_nodes: # pylint: disable=protected-access
in tensorflow\python\keras_impl\keras\utils\vis_utils.py.