Saver seems broken: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for model.ckpt-0

Updated to the last commit of 1/11. Saver seems broken. Here is the stack.
File "cnn_eval.py", line 132, in evaluate
eval_once(saver, summary_writer, logits, top_k_op,labels, names, prob, summary_op)
File "cnn_eval.py", line 43, in eval_once
saver.restore(sess, ckpt.model_checkpoint_path)
File "/usr/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 904, in restore
sess.run([self._restore_op_name], {self._filename_tensor_name: save_path})
File "/usr/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 388, in run
results = self._do_run(target_list, unique_fetch_targets, feed_dict_string)
File "/usr/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 464, in _do_run
e.code)
tensorflow.python.framework.errors.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for model.ckpt-0
[[Node: save/restore_slice_2 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_2/tensor_name, save/restore_slice_2/shape_and_slice)]]
Caused by op u'save/restore_slice_2', defined at:
File "cnn_eval.py", line 147, in 
tf.app.run()
File "/usr/lib/python2.7/site-packages/tensorflow/python/platform/default/_app.py", line 30, in run
sys.exit(main(sys.argv))
File "cnn_eval.py", line 143, in main
evaluate()
File "cnn_eval.py", line 121, in evaluate
saver = tf.train.Saver(variables_to_restore)
File "/usr/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 723, in init
restore_sequentially=restore_sequentially)
File "/usr/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 432, in build
filename_tensor, vars_to_save, restore_sequentially, reshape)
File "/usr/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 191, in _AddRestoreOps
values = self.restore_op(filename_tensor, vs, preferred_shard)
File "/usr/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 106, in restore_op
preferred_shard=preferred_shard)
File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/io_ops.py", line 192, in _restore_slice
preferred_shard, name=name)
File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 271, in _restore_slice
preferred_shard=preferred_shard, name=name)
File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/op_def_library.py", line 659, in apply_op
op_def=op_def)
File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1882, in create_op
original_op=self._default_original_op, op_def=op_def)
File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1081, in init
self._traceback = _extract_stack()