Same code, runs fine in one machine, ValueError in another.

I am running a modified version of the LFADS code available at
https://github.com/tensorflow/models/tree/master/lfads
I run the exact same code in two machines, in one it works fine, in another it throws a ValueError. Here are the two tf_env.txt
MY MACHINE (CODE WORKS)
== cat /etc/issue ===============================================
Darwin Daniels-MacBook-Pro-2.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
Mac OS X 10.12.6
== are we in docker =============================================
No
== compiler =====================================================
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
== uname -a =====================================================
Darwin Daniels-MacBook-Pro-2.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
== check pips ===================================================
numpy (1.13.1)
protobuf (3.4.0)
tensorflow (1.3.0)
tensorflow-gpu (1.1.0)
tensorflow-tensorboard (0.1.2)
== check for virtualenv =========================================
False
== tensorflow import ============================================
tf.VERSION = 1.1.0
tf.GIT_VERSION = unknown
tf.COMPILER_VERSION = unknown
Sanity check: array([1], dtype=int32)
== env ==========================================================
LD_LIBRARY_PATH is unset
DYLD_LIBRARY_PATH is unset
== nvidia-smi ===================================================
./collect.sh: line 105: nvidia-smi: command not found
== cuda libs  ===================================================
THE CLUSTER MACHINE (THROWS THE VALUE ERROR)
== cat /etc/issue ===============================================
Linux holmes 3.10.0-327.el7.x86_64 #1 SMP Thu Oct 29 17:29:29 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux
VERSION="7.3 (Maipo)"
VERSION_ID="7.3"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.3
REDHAT_SUPPORT_PRODUCT_VERSION="7.3"
== are we in docker =============================================
No
== compiler =====================================================
c++ (GCC) 6.1.0
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
== uname -a =====================================================
Linux holmes 3.10.0-327.el7.x86_64 #1 SMP Thu Oct 29 17:29:29 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux
== check pips ===================================================
numpy (1.13.1)
numpydoc (0.6.0)
protobuf (3.4.0)
tensorflow (1.3.0)
tensorflow-tensorboard (0.1.5)
== check for virtualenv =========================================
False
== tensorflow import ============================================
tf.VERSION = 1.3.0
tf.GIT_VERSION = v1.3.0-rc2-20-g0787eee
tf.COMPILER_VERSION = v1.3.0-rc2-20-g0787eee
Sanity check: array([1], dtype=int32)
== env ==========================================================
LD_LIBRARY_PATH /cm/shared/apps/slurm/16.05.8/lib64/slurm:/cm/shared/apps/slurm/16.05.8/lib64:/cm/local/apps/gcc/6.1.0/lib:/cm/local/apps/gcc/6.1.0/lib64
DYLD_LIBRARY_PATH is unset
== nvidia-smi ===================================================
./collect.sh: line 105: nvidia-smi: command not found
SOURCE CODE/ LOGS
Here is the log for the error:
Traceback (most recent call last):
.....
File "./lfads.py", line 1014, in _optimization
grads = tf.gradients(self.cost, tvars)
File "/home/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gradients_impl.py", line 562, in gradients
in_grad.set_shape(t_in.get_shape())
File "/home/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 378, in set_shape
self._shape = self._shape.merge_with(shape)
File "/home/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/tensor_shape.py", line 566, in merge_with
raise ValueError("Shapes %s and %s are not compatible" % (self, other))
ValueError: Shapes (50, ?) and (1,) are not compatible
I have diffed the files involved, to double check that they are the same. Can someone point me to what can possibly be happening?