Install tensorflow-gpu in Ubuntun16.04 meet some problem

Successfully installed tensorflow-gpu-1.3.0
t91@ubuntu:~/pengyulong$ python
Python 3.5.2 (default, Nov 17 2016, 17:05:23)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.



import tensorflow
Traceback (most recent call last):
File "/home/t91/pengyulong/tensorflow/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in 
from tensorflow.python.pywrap_tensorflow_internal import *
File "/home/t91/pengyulong/tensorflow/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in 
_pywrap_tensorflow_internal = swig_import_helper()
File "/home/t91/pengyulong/tensorflow/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
_mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
File "/home/t91/pengyulong/tensorflow/lib/python3.5/imp.py", line 242, in load_module
return load_dynamic(name, filename, file)
File "/home/t91/pengyulong/tensorflow/lib/python3.5/imp.py", line 342, in load_dynamic
return _load(spec)
ImportError: libcusolver.so.8.0: cannot open shared object file: No such file or directory



During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "", line 1, in 
File "/home/t91/pengyulong/tensorflow/lib/python3.5/site-packages/tensorflow/init.py", line 24, in 
from tensorflow.python import *
File "/home/t91/pengyulong/tensorflow/lib/python3.5/site-packages/tensorflow/python/init.py", line 49, in 
from tensorflow.python import pywrap_tensorflow
File "/home/t91/pengyulong/tensorflow/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 52, in 
raise ImportError(msg)
ImportError: Traceback (most recent call last):
File "/home/t91/pengyulong/tensorflow/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in 
from tensorflow.python.pywrap_tensorflow_internal import *
File "/home/t91/pengyulong/tensorflow/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in 
_pywrap_tensorflow_internal = swig_import_helper()
File "/home/t91/pengyulong/tensorflow/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
_mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
File "/home/t91/pengyulong/tensorflow/lib/python3.5/imp.py", line 242, in load_module
return load_dynamic(name, filename, file)
File "/home/t91/pengyulong/tensorflow/lib/python3.5/imp.py", line 342, in load_dynamic
return _load(spec)
ImportError: libcusolver.so.8.0: cannot open shared object file: No such file or directory
Failed to load the native TensorFlow runtime.
See https://www.tensorflow.org/install/install_sources#common_installation_problems
for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
P.S:run this Machine configure list:GPU:P100*4,cuda9.0,cudnn7.0