KeyError: "Couldn't find enum google.protobuf.MethodOptions.IdempotencyLevel"

Hello! I am using macOS sierra 10.2.6, with tensorflow=1.3.0. TF was working fine until sometime ago, but as of today I get the error below when trying to import. Has anyone had the same problem?
Here are the logs.

KeyError                                  Traceback (most recent call last)
 in ()
----> 1 import tensorflow
/Users/antoniocampello/anaconda/lib/python3.5/site-packages/tensorflow/init.py in ()
22
23 # pylint: disable=wildcard-import
---> 24 from tensorflow.python import *
25 # pylint: enable=wildcard-import
26
/Users/antoniocampello/anaconda/lib/python3.5/site-packages/tensorflow/python/init.py in ()
52
53 # Protocol buffers
---> 54 from tensorflow.core.framework.graph_pb2 import *
55 from tensorflow.core.framework.node_def_pb2 import *
56 from tensorflow.core.framework.summary_pb2 import *
/Users/antoniocampello/anaconda/lib/python3.5/site-packages/tensorflow/core/framework/graph_pb2.py in ()
8 from google.protobuf import reflection as _reflection
9 from google.protobuf import symbol_database as _symbol_database
---> 10 from google.protobuf import descriptor_pb2
11 # @@protoc_insertion_point(imports)
12
/Users/antoniocampello/anaconda/lib/python3.5/site-packages/google/protobuf/descriptor_pb2.py in ()
237   options=None,
238   serialized_start=4644,
--> 239   serialized_end=4724,
240 )
241 _sym_db.RegisterEnumDescriptor(_METHODOPTIONS_IDEMPOTENCYLEVEL)
/Users/antoniocampello/anaconda/lib/python3.5/site-packages/google/protobuf/descriptor.py in new(cls, name, full_name, filename, values, containing_type, options, file, serialized_start, serialized_end)
597                 serialized_start=None, serialized_end=None):
598       _message.Message._CheckCalledFromGeneratedFile()
--> 599       return _message.default_pool.FindEnumTypeByName(full_name)
600
601   def init(self, name, full_name, filename, values,
KeyError: "Couldn't find enum google.protobuf.MethodOptions.IdempotencyLevel"