Error on Windows when installed in a virtualenv that has a non-ASCII character in the path

System information


OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 x64


TensorFlow installed from (source or binary): binary from PyPI


TensorFlow version (use command below): 1.1.0


Exact command to reproduce:
from tensorflow.contrib.rnn.python.ops.gru_ops import *



Describe the problem
I encountered this when importing keras but it's reproducible with the command above. My virtualenv is in a folder that has an accented character in its name (see the log below). If I install TensorFlow globally, it works.
Source code / logs
D:\Marci\Programozás\algorimp\test>venv\scripts\python -c "from tensorflow.contrib.rnn.python.ops.gru_ops import *"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Marci\Programozás\algorimp\test\venv\lib\site-packages\tensorflow\contrib\__init__.py", line 26, in <module>
    from tensorflow.contrib import crf
  File "D:\Marci\Programozás\algorimp\test\venv\lib\site-packages\tensorflow\contrib\crf\__init__.py", line 32, in <module>
    from tensorflow.contrib.crf.python.ops.crf import _lengths_to_masks
  File "D:\Marci\Programozás\algorimp\test\venv\lib\site-packages\tensorflow\contrib\crf\python\ops\crf.py", line 44, in <module>
    from tensorflow.contrib.rnn.python.ops import core_rnn_cell
  File "D:\Marci\Programozás\algorimp\test\venv\lib\site-packages\tensorflow\contrib\rnn\__init__.py", line 80, in <module>
    from tensorflow.contrib.rnn.python.ops.gru_ops import *
  File "D:\Marci\Programozás\algorimp\test\venv\lib\site-packages\tensorflow\contrib\rnn\python\ops\gru_ops.py", line 32, in <module>
    resource_loader.get_path_to_datafile("_gru_ops.so"))
  File "D:\Marci\Programozás\algorimp\test\venv\lib\site-packages\tensorflow\contrib\util\loader.py", line 55, in load_op_library
    ret = load_library.load_op_library(path)
  File "D:\Marci\Programozás\algorimp\test\venv\lib\site-packages\tensorflow\python\framework\load_library.py", line 64, in load_op_library
    None, None, error_msg, error_code)
tensorflow.python.framework.errors_impl.NotFoundError: D:\Marci\Programozás\algorimp\test\venv\lib\site-packages\tensorflow\contrib\rnn\python\ops\_gru_ops.dll not found